newlecture-corp/newtil-css

docs/variables/border-radius.md
- border-radius 문서의 사용 예시 ExampleSection 도형 레이아웃 수정
=> border-radius 사용 예시 레이아웃 수정

packages/css/component/font.css
=> font 컴포넌트 추가

packages/css/component/button.css
=> 버튼 컴포넌트 추가

packages/css/component/item.css
=> item 컴포넌트 추가

packages/css/component/list.css
=> list 컴포넌트 추가

packages/css/component/table.css
=> 테이블 컴포넌트 추가

packages/css/component/button.css
=> 버튼 컴포넌트 prefix 추가

packages/css/component/container.css, packages/css/component/font.css, packages/css/component/item.css, packages/css/component/list.css
컨테이너, 폰트, 아이템, 리스트 컴포넌트 prefix 추가
=> 컨테이너, 폰트, 아이템, 리스트 컴포넌트 prefix 추가

packages/css/component/modal.css, packages/css/component/panel.css
=> 모달, 패널 prefix 추가

packages/css/component/toggle.css
=> 토글 컴포넌트 prefix 추가

docs/guide/customizing.md, docs/variables/border-color.md, docs/variables/border-radius.md, docs/variables/border-width.md, docs/variables/box-shadow.md, docs/variables/gap.md, docs/variables/opacity.md, docs/variables/order.md, docs/variables/z-index.md
- 오타: 스타일 재정의하기 border-radius 값 없던 것 추가
- 스타일 수정:
1. 박스 radius: 4 -> 2
2. 박스 bg-color: main-2 -> main-1
=> 문서 오타 수정 및 변수 페이지 예시 스타일 수정

packages/css/component/toggle.css
=> 토글 컴포넌트 변수 prefix 제거

packages/css/component/table.css
=> table 컴포넌트 prefix 추가

packages/css/component/list.css, packages/css/component/toggle.css
리스트, 토글 컴포넌트 클래스 및 변수 prefix 추가
=> 리스트, 토글 컴포넌트 클래스 및 변수 prefix 추가

docs/.vitepress/config.ts, docs/icons/getting-started.md, docs/icons/list.md
=> docs: icon, deco

docs/guide/getting-started-utility.md, packages/css/component/table.css, packages/css/style.css
- 스타일 재정의하기의 가칭 -> newtil-css로 수정
- style.css form import 추가
- table 컴포넌트 배경색 추가
=> 문서 및 css 수정

packages/css/root.css, packages/css/util/height.css, packages/css/util/width.css
- gap 단위를 rem에서 px로 변경
- width, height 변수 추가
- root.css width 변수 반영
- root.css width 변수 반영
=> root.css gap 단위 변경 및 width,height 변수 추가, util 반영

packages/css/component/button.css
* 버튼 기본 타입을 filled로 변경
* 버튼 사이즈별 크기를 전체적으로 크게 수정
=> 버튼 기본 타입을 filled로 변경

docs/.vitepress/config.ts, docs/guide/customizing.md, packages/css/component/form.css
input[type="text"]
+ input[type="email"]
+ input[type="number"]
+ input[type="password"]
+ input[type="search"]
+ input[type="tel"]
+ input[type="url"]
=> form 컴포넌트 input type selecor 추가

packages/css/component/toggle.css
- toggle:check 아이콘 경로 수정
- toggle-label,  toggle-label:right,  toggle-label:left,  toggle-label:top,  toggle-label:bottom 클래스 추가 및 레이아웃 정렬
```css
label:has(.n-toggle),
label:has(.n-toggle.n-toggle-label),
label:has(.n-toggle.n-toggle-label\:right) {
display: flex;
align-items: center;
flex-direction: row-reverse;
gap: var(--gap-1);
width: fit-content;
}
```
```html
<label>
토글
<input type="checkbox" class="toggle" />
</label>
<label>
토글
<input type="checkbox" class="toggle toggle-label" />
</label>
```
=> 토글 컴포넌트 toggle:check 아이콘 경로 수정, label 레이아웃 정렬 및 right, left, top, bottom 추가

packages/css/component/item.css, packages/css/component/list.css
* n-list-item type 추가 (outline, shadow, underline, none)
* n-list-item padding 추가
* n-list-item border-radius 추가
* n-item 타입추가 (outline, shadow, underline, none)
=> feat: n-list의 type, n-list-item의 padding, border-radius 추가

packages/css/component/toggle.css
- 체크 토글 아이콘 경로 수정
- 도트 토글 프리픽스 추가
=> 체크 토글 아이콘 경로 수정, 도트 토글 프리픽스 추가

packages/css/component/button.css
- button-size:3에 font-size 16px 추가
=> feat: button-size:3 font-size 추가

packages/css/component/text-box.css
텍스트박스 컴포넌트 기본 타입 클래스 추가
```css
input.n-text-box,
input.n-text-box-type\:outline,
input.n-text-box\:outline
```
=> 텍스트박스 컴포넌트 기본 타입 클래스 추가

packages/css/component/text-box.css
텍스트박스 컴포넌트 라벨 기본 위치 오른쪽 -> 왼쪽 변경
=> 텍스트박스 컴포넌트 라벨 기본 위치 오른쪽 -> 왼쪽 변경

packages/css/component/toggle.css
=> 토글 컴포넌트 라벨 left, right 속성 제거

docs/component/toggle.md
토글 컴포넌트 라벨 right, left 제거 문서 반영
=> 토글 컴포넌트 라벨 right, left 제거 문서 반영

packages/css/component/text-box.css, packages/css/component/toggle.css
- 토글
- before 
```css
label:has(.n-toggle-label){
}
```
- after
```css
label:has(.n-toggle.n-toggle-label){
}
```
- 텍스트박스
- before 
```css
label:has(.n-text-box-label){
}
```
- after
```css
label:has(.n-text-box.n-text-box-label){
}
```
=> 토글, 텍스트박스 라벨 선택자 클래스 수정

docs/component/overview.md, packages/css/component/modal.css
* 모달 사이즈 속성 제거
* 컴포넌트 모아보기 모달 z-index 수정
=> fix: 모달 사이즈 속성 제거

docs/.vitepress/config.ts, docs/guide/getting-started.md, package-lock.json, package.json
* docs
컴포넌트 시작하기
유틸리티 시작하기
컴포넌트 모아보기 페이지 분리
토글 컴포넌트
* component tag-list 추가
* fix table 컴포넌트 버그
toggle 컴포넌트 버그
modal 컴포넌트 사이즈 제거
=> release: 0.1.5

packages/css/component/text-box.css, packages/css/component/toggle.css
토글, 텍스트박스 컴포넌트 라벨 버그 및 토글 라벨 폰트 스타일 적용
=> 토글, 텍스트박스 컴포넌트 라벨 버그 및 토글 라벨 폰트 스타일 적용

docs/.vitepress/config.ts, docs/component/button.md, package-lock.json
=> docs: 버튼 컴포넌트

packages/css/component/text-box.css, packages/css/component/toggle.css
=> 토글, 텍스트박스 컴포넌트 라벨 코드 수정

packages/css/component/form.css, packages/css/component/list.css
List
1. a태그 및 Toggle 컴포넌트 outline-box 토글에도 동일하게 적용되도록 수정
2. 태그 스타일 변수 제거
3. gap 변수를 상수로 변경
Form
1. item-horizontal 변수 추가
4. 간격 조정
5. 폼 아이템 제목 너비 변수 제거
=> Form, List 컴포넌트 수정

packages/css/component/form.css, packages/css/util/align-style.css
=> align-style css 약어 클래스 수정

docs/.vitepress/config.ts, docs/component/container.md, packages/css/component/form.css
- form 컴포넌트 css 오타 수정
- 컨테이너 컴포넌트 문서 작성
=> docs: 컨테이너

packages/css/util/border.css
=> border css 약어 클래스 수정

docs/utility/background/background-attachment.md, docs/utility/background/background-position.md, packages/css/component/container.css
- bg-attch, bg-pos 약어 클래스 추가
- n-container 구조 리팩터링
=> docs: bg-attch, bg-pos 약어 클래스 추가

packages/css/util/flex.css
=> flex css 약어 클래스 수정

packages/css/util/box-sizing.css, packages/css/util/gap.css
=> gap css 약어 클래스 수정

docs/utility/box-sizing.md, packages/css/util/box-sizing.css
* box-sizing 약어 클래스 제거
* box-sizing.css 오타 수정
=> docs: box-sizing 약어 클래스 제거

packages/css/util/font.css
=> font css 약어 클래스 삭제

packages/css/util/gap.css
=> gap css 약어 클래스 삭제

docs/utility/flex/flex-basis.md, docs/utility/flex/flex-direction.md, docs/utility/flex/flex-flow.md, docs/utility/flex/flex-grow.md, docs/utility/flex/flex-shrink.md, docs/utility/flex/flex-wrap.md, docs/utility/flex/flex.md
=> docs: flex-* 계열 약어 클래스 수정

docs/utility/cursor.md
- `cursor-pointer`에서 `cursor`로 수정
-  약어클래스`cursor-p`에서 `csr`로 수정
=> docs: cursor 클래스명 수정

packages/css/util/font.css, packages/css/util/grid.css, packages/css/util/list-style.css
grid, font, list css 약어 클래스 수정
=> grid, font, list css 약어 클래스 수정

packages/css/util/font.css
=> fix: color 반응형 약어 클래스 제거

packages/css/util/margin.css
=> margin css 약어 클래스 수정

packages/css/util/object-fit.css
=> obect-fit css 약어 클래스 수정

packages/css/util/padding.css
- padding-t → p-top
- right, bottom, left 동일
=> padding css 약어 클래스 수정

packages/css/util/justify-style.css
- justify-c → js-content
- items, self에도 동일 적용
=> justify style css 약어 클래스 수정

packages/css/util/scroll.css
- scroll-b → scrl-behavior, scrl-behav
=> scroll css 약어 클래스 수정

packages/css/util/scroll.css
=> scroll css 약어 클래스 추가

packages/css/util/line-height.css
=> line-height css 약어 클래스 추가

packages/css/util/text.css
- text → txt
- line → ln
- align → al
- decoration → deco
- overflow → of
=> text css 약어 클래스 수정

packages/css/util/vertical-align.css
=> vertical-align css 약어 클래스 수정
